# Generated by Django 4.2.7 on 2023-12-02 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0002_category_tag_recipe_category_recipe_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_recipes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
